### ISSUE TITLE
mapping problem for processing GEUVADIS data

### ISSUE THREAD

**Issue by dajiangliu** [bmvdgeijn/WASP#24] opened 2015-08-01 22:52 UTC
Hello, I tried to play with WASP and run it on one of the GEUVADIS sample using python find_intersecting_snps.py . It finished sorting the bam files but stuck when it says "Starting on chromosome 1". The error message is the following: 

Can you please help me take a look? Thank you very much! 

Traceback (most recent call last):
  File "find_intersecting_snps.py", line 456, in <module>
    main()
  File "find_intersecting_snps.py", line 449, in main
    bam_data.empty_slot_paired()
  File "find_intersecting_snps.py", line 260, in empty_slot_paired
    seq1s=self.check_for_snps(read,0)
  File "find_intersecting_snps.py", line 299, in check_for_snps
    for cigar in read.cigar:
TypeError: 'NoneType' object is not iterable

**Comment by bmvdgeijn** [comment] 2015-08-03 18:31
It looks like for some reason that read doesn't have a cigar string.  Is it
possible that you still have unmapped or very low mapping quality reads in
your bam file?

**Comment by dajiangliu** [comment] 2015-08-03 19:43
Hi, Bryce,

 

Thank you very much for getting back to me! I think the CIGAR column are there. 

 

TO help you diagnose the issue, I have made a small exemplar data from the entire geuvadis data. The issue persists. The command I used was 

python find_intersecting_snps.py -p NA12778.RG.1000.bam SNP_files/ 

 

The exemplar dataset is here:

https://www.dropbox.com/sh/0bo6cbo1csyjub7/AAA9Dbj35nrfHguBkteRQsgAa?dl=0 

 

The error message is pretty much the same:

 

tarting on chromosome 1

Traceback (most recent call last):

  File "find_intersecting_snps.py", line 456, in <module>

    main()

  File "find_intersecting_snps.py", line 449, in main

    bam_data.empty_slot_paired()

  File "find_intersecting_snps.py", line 260, in empty_slot_paired

    seq1s=self.check_for_snps(read,0)

  File "find_intersecting_snps.py", line 299, in check_for_snps

    for cigar in read.cigar:

TypeError: 'NoneType' object is not iterable

 

Thanks a lot!

 

Dajiang

**Comment by gmcvicker** [comment] 2015-08-03 20:06
Hi Dajiang,

I downloaded your example data files but was not able to reproduce your problem.

What version of pysam are you using? Can you do the following within python:
import pysam
print pysam.__version__

I am using pysam 0.8.2.1, but I wonder if the issue you are having is specific to a certain version.

**Comment by dajiangliu** [comment] 2015-08-04 00:07
Hi, Graham,
Thank you very much for the advice! Yes, indeed the version of pysam caused the problem. The program can run now. Looking forward to seeing the result now. Thanks again! 

All the best,Dajiang
CallSend SMSCall from mobileAdd to SkypeYou'll need Skype CreditFree via SkypeCallSend SMSCall from mobileAdd to SkypeYou'll need Skype CreditFree via SkypeCallSend SMSCall from mobileAdd to SkypeYou'll need Skype CreditFree via Skype

Date: Mon, 3 Aug 2015 13:06:18 -0700

**Comment by gmcvicker** [comment] 2015-08-04 14:17
Hi Dajiang,

Out of curiosity what version of pysam did you run into problems with? We'd like to document the version that people should use (or make the software more flexible so it can work with different versions). Thanks!

Graham

**Comment by dajiangliu** [comment] 2015-08-04 21:14
Hi, Graham,

 

Thank you very much for your help again! The version of pysam I used was 0.7.5, which seems to be causing the crash in the previous run. Thanks!

**Comment by gmcvicker** [comment] 2016-09-06 00:53
Closing issue, because related to problem with old pysam version, not WASP.

**Closed by gmcvicker** 2016-09-06 00:53 UTC
